[package]
name = "bf2wasm"
version = "0.1.0"
authors = ["m-shaka <buddha0818@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
wabt = "0.10.0"
